using System.Diagnostics;
using System.Text;
using RecipesManage.Application.Dtos;
using RecipesManage.Domain.Batches;
using RecipesManage.Domain.Recipes;
using RecipesManage.Infrastructure.Records;
using Xunit;

namespace RecipesManage.Execution.Tests;

public sealed class BatchRecordPdfTests
{
    [Fact]
    public void Render_EmitsPdfAIdentifierAndHandshakeArchive()
    {
        var pdf = new BatchRecordPdf().Render(SampleRecord());
        Assert.True(pdf.Length > 200);
        var ascii = Encoding.ASCII.GetString(pdf);
        var latin = Encoding.Latin1.GetString(pdf);
        Assert.StartsWith("%PDF", ascii);
        Assert.Contains("endobj", ascii, StringComparison.Ordinal);
        Assert.Contains("BPDF1", latin, StringComparison.Ordinal);
        Assert.True(
            ascii.Contains("pdfaid", StringComparison.OrdinalIgnoreCase) ||
            ascii.Contains("GTS_PDFA1", StringComparison.OrdinalIgnoreCase) ||
            ascii.Contains("<pdfaid:part>", StringComparison.OrdinalIgnoreCase) ||
            latin.Contains("pdfaid:part", StringComparison.OrdinalIgnoreCase),
            "PDF/A identifier (pdfaid / GTS_PDFA1) missing from generated bytes.");
    }

    [Fact]
    public async Task Render_PassesVeraPdfPdfA3b_WhenCliPresent()
    {
        var java = ResolveVeraPdfJava();
        var jar = ResolveVeraPdfJar();
        if (java is null || jar is null)
            return;

        var pdfPath = Path.Combine(Path.GetTempPath(), $"brmes-ebr-{Guid.NewGuid():N}.pdf");
        await File.WriteAllBytesAsync(pdfPath, new BatchRecordPdf().Render(SampleRecord()));
        try
        {
            var psi = new ProcessStartInfo(java)
            {
                ArgumentList = { "-cp", jar, "org.verapdf.apps.GreenfieldCliWrapper", "--format", "text", "-f", "0", pdfPath },
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using var proc = Process.Start(psi) ?? throw new InvalidOperationException("未能启动 veraPDF。");
            var stdoutTask = proc.StandardOutput.ReadToEndAsync();
            var stderrTask = proc.StandardError.ReadToEndAsync();
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));
            await proc.WaitForExitAsync(cts.Token);
            var stdout = await stdoutTask;
            _ = await stderrTask;
            Assert.Equal(0, proc.ExitCode);
            Assert.Contains("PASS", stdout, StringComparison.Ordinal);
            Assert.Contains("3b", stdout, StringComparison.Ordinal);
        }
        finally
        {
            File.Delete(pdfPath);
        }
    }

    private static string? ResolveVeraPdfJava()
    {
        var env = Environment.GetEnvironmentVariable("BRMES_JAVA");
        if (!string.IsNullOrWhiteSpace(env) && File.Exists(env))
            return env;
        var bundled = Path.Combine(Path.GetTempPath(), "brmes-verify", "jdk-17.0.18+8-jre", "bin", "java.exe");
        return File.Exists(bundled) ? bundled : null;
    }

    private static string? ResolveVeraPdfJar()
    {
        var env = Environment.GetEnvironmentVariable("BRMES_VERAPDF_JAR");
        if (!string.IsNullOrWhiteSpace(env) && File.Exists(env))
            return env;
        var bundled = Path.Combine(Path.GetTempPath(), "brmes-verify", "greenfield-apps-1.28.1.jar");
        return File.Exists(bundled) ? bundled : null;
    }

    private static BatchRecordDto SampleRecord()
    {
        var stepId = Guid.NewGuid();
        var snapshot = new ControlRecipeSnapshot
        {
            MasterRecipeId = Guid.NewGuid(),
            RecipeVersionId = Guid.NewGuid(),
            VersionNumber = 1,
            RecipeCode = "AL-HT-T6",
            RecipeName = "热处理",
            ProductCode = "AL6061",
            ProductName = "锻件",
            FrozenAt = DateTimeOffset.UtcNow,
            IntegrityHash = "abc",
            Steps =
            [
                new SnapshotStep
                {
                    StepId = stepId,
                    Code = "S10",
                    Name = "升温",
                    Type = StepType.Heat,
                    Ordinal = 0,
                    WatchdogSeconds = 30,
                    UnitProcedure = "UP-01 热处理单元",
                    Parameters = [new SnapshotParameter { Name = "目标温度", EngineeringUnit = "℃", Setpoint = 530, WriteToPlc = true, ArchiveAsQuality = true }]
                }
            ]
        };
        return new BatchRecordDto(
            Guid.NewGuid(),
            "BPDF1",
            BatchStatus.Completed,
            "Valid",
            snapshot,
            [new StepExecutionDto(stepId, "S10", "升温", StepType.Heat, 0, "Completed", DateTimeOffset.UtcNow, DateTimeOffset.UtcNow, """{"目标温度":529.4}""")],
            [new HandshakeLogDto(DateTimeOffset.UtcNow, "S10", "WritingParameters", "write", "Step_ID=10", 4)],
            [new SampleDto(DateTimeOffset.UtcNow, "Temperature", 529.4, "℃", stepId)],
            [],
            [new ApprovalDto(Guid.NewGuid(), ApprovalLevel.Quality, ApprovalDecision.Approved, "qa", "ok", DateTimeOffset.UtcNow, "质量批准")],
            [],
            DateTimeOffset.UtcNow,
            ControlRecipeWritePlan.FromSnapshot(snapshot).Select(i => new PlcWritePlanDto(
                i.StepId, i.StepCode, i.StepName, i.StepType,
                i.PlcStepId, i.PlcStepType, i.Parameters, i.WriteToPlc, i.Policy)).ToList());
    }
}
