<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\RecipesManage.Application\RecipesManage.Application.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>
</Project>
